### ISSUE TITLE
Polaris LAMMPS compilatuib with CUDA MPS

### ISSUE THREAD

**Issue by williamyxl** [globus-labs/mof-generation-at-scale#29]
I have compiled a version of LAMMPS on both NCSA Delta and ALCF Polaris with MPS enabled. The executable works on single simulation. 

I tried to follow the MPS guideline from ALCF docs: [https://docs.alcf.anl.gov/running-jobs/example-job-scripts/?h=mps#using-mps-in-multi-node-jobs](https://docs.alcf.anl.gov/running-jobs/example-job-scripts/?h=mps#using-mps-in-multi-node-jobs)

But I'm getting the "Cannot find MPS control daemon process" error. 

```
xiaoliyan@x3102c0s13b1n0:/lus/grand/projects/RAPINS/xiaoliyan/lmp20230802stb/test-gpu/test-multi-mof/ZnZn2-L11_18_6-L11_1_6-L18_17_7-cat3_mpi1-omp1/1_inst> nvidia-cuda-mps-control -d
xiaoliyan@x3102c0s13b1n0:/lus/grand/projects/RAPINS/xiaoliyan/lmp20230802stb/test-gpu/test-multi-mof/ZnZn2-L11_18_6-L11_1_6-L18_17_7-cat3_mpi1-omp1/1_inst> echo "start_server -uid $( id -u )" | nvidia-cuda-mps-control
Cannot find MPS control daemon process
```

I also tested setting the GPU mode to EXCLUSIVE_PROCESS, like described here: [https://stackoverflow.com/questions/34709749/how-do-i-use-nvidia-multi-process-service-mps-to-run-multiple-non-mpi-cuda-app](https://stackoverflow.com/questions/34709749/how-do-i-use-nvidia-multi-process-service-mps-to-run-multiple-non-mpi-cuda-app)

but I'm getting insufficient privilege error. 

```
xiaoliyan@x3102c0s13b1n0:/lus/grand/projects/RAPINS/xiaoliyan/lmp20230802stb/test-gpu/test-multi-mof/ZnZn2-L11_18_6-L11_1_6-L18_17_7-cat3_mpi1-omp1/1_inst> nvidia-smi -i 0 -c EXCLUSIVE_PROCESS
Unable to set the compute mode for GPU 00000000:07:00.0: Insufficient Permissions
Terminating early due to previous errors.
```

The compilation details are here: [https://gitlab.com/doublylinkedlist/compilation_notes/-/blob/main/alcf/polaris_lmp](https://gitlab.com/doublylinkedlist/compilation_notes/-/blob/main/alcf/polaris_lmp
)

**Comment by WardLT** [comment]
Closing as we've got the GPU lammps working on both Polaris and Sunspot
